### ISSUE TITLE
Terminal plotting

### ISSUE THREAD

**Issue by bbelderbos** [PyBites-Open-Source/git-stats#1]
This can be improved:

<img width="2672" alt="image" src="https://user-images.githubusercontent.com/387927/194558581-f29bbccd-364a-4080-8203-329179751302.png">

We could use plotext for example: https://pybit.es/articles/terminal-plotting-with-plotext/

**Comment by claytonjhamilton** [comment]
Hello @bbelderbos, what do you think about using the UTF-8 character "█" to generate bars? One approach could include making the bar entirely fill the max value in the series and the other bars would fill (approximately) their percentage of the 
max. If less than a certain percentage of the max, a skinny bar could be used as seen below.

<img width="562" alt="image" src="https://user-images.githubusercontent.com/51751663/194731960-1cd45ce2-4642-4a83-8a73-5e7098fbf014.png">

I'd like to try to implement if you're open to the idea?

**Comment by bbelderbos** [comment]
Awesome, thanks 🙏  @claytonjhamilton, looks nice, much better than what we have now :)
Let's focus on this first, but if you see other areas of improvement with the report, let me know ...

**Comment by bbelderbos** [comment]
Nice work @claytonjhamilton I finally used this tool again and was delighted seeing this in my terminal 😍

<img width="1226" alt="image" src="https://github.com/PyBites-Open-Source/git-stats/assets/387927/8ad8841a-d017-4574-accc-5cde459d5ced">
