### ISSUE TITLE
.gitignore update

### ISSUE THREAD

**Issue by claytonjhamilton** [PyBites-Open-Source/git-stats#3]
My work on another issue resulted in accumulation of files that needn't be pushed. 

May I fix this by updating the current .gitnore with this file?
[https://github.com/github/gitignore/blob/main/Python.gitignore](https://github.com/github/gitignore/blob/main/Python.gitignore)

Thank you!

**Comment by bbelderbos** [comment]
@claytonjhamilton yes please go ahead, feel free to open a new PR. Thanks.
